### ISSUE TITLE
Can stubs work without mypy with pyright?

### ISSUE THREAD

**Issue by rmzr7** [dropbox/sqlalchemy-stubs#164] opened 2020-07-18 16:33 UTC
Hi, I was wondering if the subs would work without mypy, for pyright?

**Comment by killthekitten** [comment] 2020-07-20 11:49
Duplicate of #140

**Comment by ilevkivskyi** [comment] 2020-07-22 10:15
> Duplicate of #140

Closing as such.

**Closed by ilevkivskyi** 2020-07-22 10:15 UTC
