### ISSUE TITLE
Model instance attributes have correct types when accessed, but not when compared structurally to another class

### ISSUE THREAD

**Issue by ckarnell** [dropbox/sqlalchemy-stubs#134] opened 2019-12-18 16:59 UTC
Currently when you access an attribute on a model, its type gets converted to the expected Python type. However, since this uses the plugin hook for attribute access, that means when structural typing is attempted, it doesn't match up.

Here's an example illustrating my point.
```
from typing_extensions import Protocol
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer

class UserStructure(Protocol):
    id: int

Base = declarative_base()

class User(Base):
    id = Column(Integer, primary_key=True)

user: UserStructure = User() # Incompatible types in assignment (expression has type "User", variable has type "UserStructure")  [assignment]
# Following member(s) of "User" have conflicts:
#    id: expected "int", got "Column[int]"
```

Even though `reveal_type(user.id)` shows `int`.

**Comment by ilevkivskyi** [comment] 2019-12-19 15:35
This is actually caused by mypy issue https://github.com/python/mypy/issues/7724. But I will keep this open as an important example.

**Comment by ilevkivskyi** [comment] 2019-12-19 15:36
Actually there is a dedicated issue already for this case https://github.com/python/mypy/issues/5481, so this can be closed as a duplicate.

**Closed by ilevkivskyi** 2019-12-19 15:36 UTC
