### ISSUE TITLE
Unexpected keyword argument

### ISSUE THREAD

**Issue by mehdigmira** [dropbox/sqlalchemy-stubs#40] opened 2018-12-06 18:39 UTC
Hello,
With the latest release of mypy and the master branch of sqlalchemy-stubs, this code causes mypy to raise a "error: Unexpected keyword argument "name" for "User""
Is there smth I can do to avoid these errors ?
```
from sqlalchemy import CheckConstraint, Column, Integer, String
from sqlalchemy.ext.declarative import as_declarative

@as_declarative()
class Base:
    pass


class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    name = Column(String)


user = User(name="xx")
```

**Comment by ilevkivskyi** [comment] 2018-12-06 18:59
Duplicate of https://github.com/dropbox/sqlalchemy-stubs/issues/5

(I have this working locally, but it requires more polish before publishing.)

**Closed by ilevkivskyi** 2018-12-06 18:59 UTC

**Comment by mehdigmira** [comment] 2018-12-06 20:55
Is there a workaround ?
I've tried the version below. I no longer have the error, but then mypy doesn' log errors he should be logging.

```python
from typing import Any

from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()  # type: Any


class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    name = Column(String)


class Address(Base):
    __tablename__ = 'addresses'
    id = Column(Integer, primary_key=True)
    name = Column(String)


def f() -> Address:
    user = User(name="xx")
    return user  # mypy should log an error here but doesn't

```

**Comment by mehdigmira** [comment] 2018-12-10 09:02
@ilevkivskyi Can I have ave some feedback on this if you have some time ?

**Comment by ilevkivskyi** [comment] 2018-12-10 10:13
There is no way to have no false positives and no false negatives before the plugin is ready. You can use `@as_declarative` instead however.

**Comment by mehdigmira** [comment] 2018-12-10 10:19
But then I have a ton of ""error: Unexpected keyword argument "name" for "User"" errors. It would require me an hour of "type: ignore" to silence them ^^.
I guess The only way is to wait for #5 to be resolved.

**Comment by ilevkivskyi** [comment] 2018-12-10 10:21
```python
@as_declarative
class Base:
    def __init__(self, *args, **kwargs) -> None: ...
```
